name: 🧪 Test Solution 🧪

on:

  pull_request:
    types: [opened, reopened, synchronize]
    branches:
    - "**"

jobs:
  dotnet-test:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: './Scribbly.Broker.slnx'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore $SOLUTION
      
    - name: Build Solution
      run: dotnet build $SOLUTION --no-restore

    - name: Test Solution
      run: dotnet test $SOLUTION --no-restore --verbosity normal